"""
Publish command for GitHub Pages publishing.
"""

import sys
from pathlib import Path
import click

from gatowiki.cli.utils.errors import (
    RepositoryError,
    FileSystemError,
    handle_error,
    EXIT_SUCCESS,
)
from gatowiki.cli.utils.repo_validator import is_git_repository
from gatowiki.cli.utils.logging import create_logger


@click.command(name="publish")
@click.option(
    "--output",
    "-o",
    type=click.Path(exists=True),
    default="docs",
    help="Documentation directory to publish (default: ./docs)",
)
@click.option(
    "--github-pages",
    is_flag=True,
    help="Generate index.html for GitHub Pages deployment",
)
@click.option(
    "--create-branch",
    is_flag=True,
    help="Create gh-pages branch for GitHub Pages",
)
@click.option(
    "--verbose",
    "-v",
    is_flag=True,
    help="Show detailed progress and debug information",
)
@click.pass_context
def publish_command(
    ctx,
    output: str,
    github_pages: bool,
    create_branch: bool,
    verbose: bool
):
    """
    Publish generated documentation to GitHub Pages.
    
    This command assumes documentation has already been generated by GitHub
    Copilot agents. It handles HTML viewer generation, gh-pages branch
    creation, and git operations.
    
    Examples:
    
    \b
    # Generate HTML viewer
    $ gatowiki publish --github-pages
    
    \b
    # Create gh-pages branch
    $ gatowiki publish --github-pages --create-branch
    
    \b
    # Publish from custom directory
    $ gatowiki publish --output custom-docs --github-pages
    """
    logger = create_logger(verbose=verbose)
    
    try:
        # Validate output directory
        output_dir = Path(output).expanduser().resolve()
        
        if not output_dir.exists():
            raise FileSystemError(
                f"Documentation directory not found: {output_dir}\n\n"
                "Please generate documentation first using GitHub Copilot agents."
            )
        
        # Check for documentation files
        md_files = list(output_dir.glob("*.md"))
        if not md_files:
            raise FileSystemError(
                f"No documentation files found in {output_dir}\n\n"
                "Please generate documentation first using GitHub Copilot agents."
            )
        
        logger.success(f"Found {len(md_files)} documentation files")
        
        # Get repository path (parent of output dir or current dir)
        repo_path = Path.cwd()
        
        # Check git repository
        if create_branch and not is_git_repository(repo_path):
            raise RepositoryError(
                "Not a git repository.\n\n"
                "The --create-branch flag requires a git repository.\n\n"
                "To initialize a git repository: git init"
            )
        
        # Generate HTML viewer
        if github_pages:
            logger.step("Generating HTML viewer...", 1, 2 if create_branch else 1)
            
            from gatowiki.cli.html_generator import HTMLGenerator
            
            html_generator = HTMLGenerator()
            repo_info = html_generator.detect_repository_info(repo_path)
            
            output_path = output_dir / "index.html"
            html_generator.generate(
                output_path=output_path,
                title=repo_info['name'],
                repository_url=repo_info['url'],
                github_pages_url=repo_info['github_pages_url'],
                docs_dir=output_dir
            )
            
            logger.success(f"Generated {output_path}")
        
        # Create gh-pages branch
        if create_branch:
            logger.step("Creating gh-pages branch...", 2, 2)
            
            from gatowiki.cli.git_manager import GitManager
            
            git_manager = GitManager(repo_path)
            
            # Check clean working directory
            is_clean, status_msg = git_manager.check_clean_working_directory()
            if not is_clean:
                logger.warning(
                    "Working directory has uncommitted changes.\n"
                    f"{status_msg}\n\n"
                    "Consider committing changes before creating gh-pages branch."
                )
                
                if not click.confirm("Continue anyway?", default=False):
                    logger.info("Cancelled by user.")
                    sys.exit(EXIT_SUCCESS)
            
            # Create branch
            branch_name = git_manager.create_documentation_branch()
            logger.success(f"Created branch: {branch_name}")
            
            # Display instructions
            click.echo()
            click.secho("✓ GitHub Pages setup complete!", fg="green", bold=True)
            click.echo()
            click.echo(f"  Branch:         {branch_name}")
            click.echo(f"  Documentation:  {output_dir}")
            click.echo()
            click.secho("Next steps:", fg="cyan", bold=True)
            click.echo(f"  1. Push branch: git push origin {branch_name}")
            click.echo("  2. Enable GitHub Pages in repository settings")
            click.echo(f"  3. Set source to '{branch_name}' branch")
            
            if repo_info.get('github_pages_url'):
                click.echo()
                click.echo(f"  Your docs will be available at:")
                click.echo(f"  {repo_info['github_pages_url']}")
            
            click.echo()
        elif github_pages:
            # Just HTML generation
            click.echo()
            click.secho("✓ HTML viewer generated!", fg="green", bold=True)
            click.echo()
            click.echo(f"  File:  {output_dir / 'index.html'}")
            click.echo()
            click.secho("Next steps:", fg="cyan", bold=True)
            click.echo("  • Open index.html in a browser to view documentation")
            click.echo("  • Or run: gatowiki publish --create-branch to set up GitHub Pages")
            click.echo()
        else:
            # No action taken
            click.echo()
            click.secho("No action taken.", fg="yellow")
            click.echo()
            click.echo("Use --github-pages to generate HTML viewer")
            click.echo("Use --create-branch to create gh-pages branch")
            click.echo()
        
    except RepositoryError as e:
        logger.error(e.message)
        sys.exit(e.exit_code)
    except FileSystemError as e:
        logger.error(e.message)
        sys.exit(e.exit_code)
    except KeyboardInterrupt:
        click.echo("\n\nInterrupted by user")
        sys.exit(130)
    except Exception as e:
        sys.exit(handle_error(e, verbose=verbose))
